### ISSUE TITLE
Issues with links

### ISSUE THREAD

**Issue by Czar-Ec** [OliverMBathurst/olivermbathurst.github.io#1]
I Have no idea how this has happened but on Chrome, it doesn't navigate to the link unless you press on the red rectangle region
![image](https://user-images.githubusercontent.com/32554382/83956433-e4a61e80-a855-11ea-85f3-1a0f6e004191.png)

It doesn't work if you press anywhere else

**Comment by OliverMBathurst** [comment]
Thanks Czar, the issue should be fixed now, the invisible links on the homepage were displacing the normal links.
